/** Declaration file generated by dts-gen */

export function provider(options: any): any;

export function server(options: any): any;

export namespace provider {
    const prototype: {
    };

}

export namespace server {
    const prototype: {
    };

}

