/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_orbs_cryptosdk_CryptoSDK */

#ifndef _Included_com_orbs_cryptosdk_CryptoSDK
#define _Included_com_orbs_cryptosdk_CryptoSDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_orbs_cryptosdk_CryptoSDK
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_orbs_cryptosdk_CryptoSDK_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
