/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_orbs_cryptosdk_ED25519Key */

#ifndef _Included_com_orbs_cryptosdk_ED25519Key
#define _Included_com_orbs_cryptosdk_ED25519Key
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_orbs_cryptosdk_ED25519Key
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_orbs_cryptosdk_ED25519Key_init__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_orbs_cryptosdk_ED25519Key
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_orbs_cryptosdk_ED25519Key_init__
  (JNIEnv *, jobject);

/*
 * Class:     com_orbs_cryptosdk_ED25519Key
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_orbs_cryptosdk_ED25519Key_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_orbs_cryptosdk_ED25519Key
 * Method:    getPublicKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_orbs_cryptosdk_ED25519Key_getPublicKey
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
