/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_orbs_cryptosdk_ED25519Key */

#ifndef _Included_com_orbs_cryptosdk_ED25519Key
#define _Included_com_orbs_cryptosdk_ED25519Key
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_orbs_cryptosdk_ED25519Key
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_orbs_cryptosdk_ED25519Key_init__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_orbs_cryptosdk_ED25519Key
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_orbs_cryptosdk_ED25519Key_init__Ljava_lang_String_2Ljava_lang_String_2
    (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_orbs_cryptosdk_ED25519Key
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_orbs_cryptosdk_ED25519Key_init__
  (JNIEnv *, jobject);

/*
 * Class:     com_orbs_cryptosdk_ED25519Key
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_orbs_cryptosdk_ED25519Key_finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_orbs_cryptosdk_ED25519Key
 * Method:    getPublicKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_orbs_cryptosdk_ED25519Key_getPublicKey
  (JNIEnv *, jobject);

/*
 * Class:     com_orbs_cryptosdk_ED25519Key
 * Method:    hasPrivateKey
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_orbs_cryptosdk_ED25519Key_hasPrivateKey
    (JNIEnv *, jobject);

/*
 * Class:     com_orbs_cryptosdk_ED25519Key
 * Method:    sign
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_orbs_cryptosdk_ED25519Key_sign
    (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_orbs_cryptosdk_ED25519Key
 * Method:    verify
 * Signature: ([B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_orbs_cryptosdk_ED25519Key_verify
    (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
