/** Declaration file generated by dts-gen */

export const supportsImportCallback: boolean;

export const supportsMulti: boolean;

export const supportsStandard: boolean;

export function compile(input: any, optimise: any, readCallback?: any): any;

export function compileStandard(input: any, readCallback?: any): any;

export function compileStandardWrapper(input: any, readCallback?: any): any;

export function license(...args: any[]): any;

export function linkBytecode(bytecode: any, libraries: any): any;

export function loadRemoteVersion(versionString: any, cb: any): void;

export function setupMethods(soljson: any): any;

export function version(...args: any[]): any;

export namespace compile {
  const prototype: {
  };

}

export namespace compileStandard {
  const prototype: {
  };

}

export namespace compileStandardWrapper {
  const prototype: {
  };

}

export namespace license {
  const prototype: {
  };

}

export namespace linkBytecode {
  const prototype: {
  };

}

export namespace loadRemoteVersion {
  const prototype: {
  };

}

export namespace setupMethods {
  const prototype: {
  };

}

export namespace version {
  const prototype: {
  };

}

