/**
 * Copyright 2018 the orbs-network-typescript authors
 * This file is part of the orbs-network-typescript library in the Orbs project.
 *
 * This source code is licensed under the MIT license found in the LICENSE file in the root directory of this source tree.
 * The above notice should be included in all copies or substantial portions of the software.
 */

/** Declaration file generated by dts-gen */

export const supportsImportCallback: boolean;

export const supportsMulti: boolean;

export const supportsStandard: boolean;

export function compile(input: any, optimise: any, readCallback?: any): any;

export function compileStandard(input: any, readCallback?: any): any;

export function compileStandardWrapper(input: any, readCallback?: any): any;

export function license(...args: any[]): any;

export function linkBytecode(bytecode: any, libraries: any): any;

export function loadRemoteVersion(versionString: any, cb: any): void;

export function setupMethods(soljson: any): any;

export function version(...args: any[]): any;

export namespace compile {
  const prototype: {
  };

}

export namespace compileStandard {
  const prototype: {
  };

}

export namespace compileStandardWrapper {
  const prototype: {
  };

}

export namespace license {
  const prototype: {
  };

}

export namespace linkBytecode {
  const prototype: {
  };

}

export namespace loadRemoteVersion {
  const prototype: {
  };

}

export namespace setupMethods {
  const prototype: {
  };

}

export namespace version {
  const prototype: {
  };

}

