/** Declaration file generated by dts-gen */

export = uncaught_exception;

declare function uncaught_exception(options: any): any;

declare namespace uncaught_exception {
    const prototype: {
    };
}
