version: '2.1'
services:
  basic-simulation:
    build: .
    command: node simulate/src/index.js discovery
    environment:
      E2E_PUBLIC_API_ENDPOINT: 0.0.0.0:51151
    volumes:
      - ./config:/opt/orbs/config/
      - ./projects/common-library-typescript/dist:/opt/orbs/projects/common-library-typescript/dist/
      - ./projects/consensus-service-typescript/dist:/opt/orbs/projects/consensus-service-typescript/dist/
      - ./projects/gossip-service-typescript/dist:/opt/orbs/projects/gossip-service-typescript/dist/
      - ./projects/virtual-machine-service-typescript/dist:/opt/orbs/projects/virtual-machine-service-typescript/dist/
      - ./e2e/:/opt/orbs/e2e/
      - ./projects/common-library-typescript/node_modules/grpc/src/client.js:/opt/orbs/projects/common-library-typescript/node_modules/grpc/src/client.js
    networks:
      basic-network:

networks:
  basic-network:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
      - subnet: 172.1.1.0/24
