version: '2'

services:
  consensus-bliny:
    extends:
      file: docker-compose.test.base.yml
      service: consensus
    environment:
      NODE_NAME: bliny
    networks: 
      bliny:
        ipv4_address: 172.100.1.15
    volumes:
      - ./deploy/dummy-keys/private/bliny:/opt/orbs/config/topologies/discovery/node1/config/test-private-key
    extra_hosts:
      - consensus:172.100.1.15
      - public-api:172.100.1.16
      - state-storage:172.100.1.17
      - virtual-machine:172.100.1.18
      - block-storage:172.100.1.19
      - gossip:172.100.1.20

  public-api-bliny:
    extends:
      file: docker-compose.test.base.yml
      service: public-api
    environment:
      NODE_NAME: bliny
    networks: 
      bliny:
        ipv4_address: 172.100.1.16
    volumes:
      - ./deploy/dummy-keys/private/bliny:/opt/orbs/config/topologies/discovery/node1/config/test-private-key
    extra_hosts:
      - consensus:172.100.1.15
      - public-api:172.100.1.16
      - state-storage:172.100.1.17
      - virtual-machine:172.100.1.18
      - block-storage:172.100.1.19
      - gossip:172.100.1.20

  state-storage-bliny:
    extends:
      file: docker-compose.test.base.yml
      service: state-storage
    environment:
      NODE_NAME: bliny
    networks: 
      bliny:
        ipv4_address: 172.100.1.17
    extra_hosts:
      - consensus:172.100.1.15
      - public-api:172.100.1.16
      - state-storage:172.100.1.17
      - virtual-machine:172.100.1.18
      - block-storage:172.100.1.19
      - gossip:172.100.1.20

  virtual-machine-bliny:
    extends:
      file: docker-compose.test.base.yml
      service: virtual-machine
    environment:
      NODE_NAME: bliny
    networks: 
      bliny:
        ipv4_address: 172.100.1.18
    extra_hosts:
      - consensus:172.100.1.15
      - public-api:172.100.1.16
      - state-storage:172.100.1.17
      - virtual-machine:172.100.1.18
      - block-storage:172.100.1.19
      - gossip:172.100.1.20

  block-storage-bliny:
    extends:
      file: docker-compose.test.base.yml
      service: block-storage
    environment:
      NODE_NAME: bliny
    networks: 
      bliny:
        ipv4_address: 172.100.1.19
    extra_hosts:
      - consensus:172.100.1.15
      - public-api:172.100.1.16
      - state-storage:172.100.1.17
      - virtual-machine:172.100.1.18
      - block-storage:172.100.1.19
      - gossip:172.100.1.20

  gossip-bliny:
    extends:
      file: docker-compose.test.base.yml
      service: gossip
    environment:
      NODE_NAME: bliny
      NODE_IP: 172.2.1.2
    networks: 
      common:
        ipv4_address: 172.2.1.2
      bliny:
        ipv4_address: 172.100.1.20
    volumes:
      - ./deploy/dummy-keys/private/bliny:/opt/orbs/config/topologies/discovery/node1/config/test-private-key
    extra_hosts:
      - consensus:172.100.1.15
      - public-api:172.100.1.16
      - state-storage:172.100.1.17
      - virtual-machine:172.100.1.18
      - block-storage:172.100.1.19
      - gossip:172.100.1.20
      # - block-storage-bliny:block-storage
      # - virtual-machine-bliny:virtual-machine
      # - state-storage-bliny:state-storage
      # - public-api-bliny:public-api
      # - consensus-bliny:consensus


networks:
  common:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.2.1.0/24
  bliny:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.100.1.0/24
  node2:
  node3:
  node4:
  node5:
  node6:
