version: '2'

services:
  consensus-_NODE_NAME_:
    extends:
      file: docker-compose.test.base.yml
      service: consensus
    environment:
      NODE_NAME: _NODE_NAME_
    networks: 
      _NODE_NAME_:
        ipv4_address: _PRIVATE_NETWORK_.15
    volumes:
      - ./deploy/dummy-keys/private/_NODE_NAME_:/opt/orbs/config/topologies/discovery/node1/config/test-private-key
    extra_hosts:
      - consensus:_PRIVATE_NETWORK_.15
      - public-api:_PRIVATE_NETWORK_.16
      - state-storage:_PRIVATE_NETWORK_.17
      - virtual-machine:_PRIVATE_NETWORK_.18
      - block-storage:_PRIVATE_NETWORK_.19
      - gossip:_PRIVATE_NETWORK_.20

  public-api-_NODE_NAME_:
    extends:
      file: docker-compose.test.base.yml
      service: public-api
    environment:
      NODE_NAME: _NODE_NAME_
    networks: 
      _NODE_NAME_:
        ipv4_address: _PRIVATE_NETWORK_.16
    volumes:
      - ./deploy/dummy-keys/private/_NODE_NAME_:/opt/orbs/config/topologies/discovery/node1/config/test-private-key
    extra_hosts:
      - consensus:_PRIVATE_NETWORK_.15
      - public-api:_PRIVATE_NETWORK_.16
      - state-storage:_PRIVATE_NETWORK_.17
      - virtual-machine:_PRIVATE_NETWORK_.18
      - block-storage:_PRIVATE_NETWORK_.19
      - gossip:_PRIVATE_NETWORK_.20

  state-storage-_NODE_NAME_:
    extends:
      file: docker-compose.test.base.yml
      service: state-storage
    environment:
      NODE_NAME: _NODE_NAME_
    networks: 
      _NODE_NAME_:
        ipv4_address: _PRIVATE_NETWORK_.17
    extra_hosts:
      - consensus:_PRIVATE_NETWORK_.15
      - public-api:_PRIVATE_NETWORK_.16
      - state-storage:_PRIVATE_NETWORK_.17
      - virtual-machine:_PRIVATE_NETWORK_.18
      - block-storage:_PRIVATE_NETWORK_.19
      - gossip:_PRIVATE_NETWORK_.20

  virtual-machine-_NODE_NAME_:
    extends:
      file: docker-compose.test.base.yml
      service: virtual-machine
    environment:
      NODE_NAME: _NODE_NAME_
    networks: 
      _NODE_NAME_:
        ipv4_address: _PRIVATE_NETWORK_.18
    extra_hosts:
      - consensus:_PRIVATE_NETWORK_.15
      - public-api:_PRIVATE_NETWORK_.16
      - state-storage:_PRIVATE_NETWORK_.17
      - virtual-machine:_PRIVATE_NETWORK_.18
      - block-storage:_PRIVATE_NETWORK_.19
      - gossip:_PRIVATE_NETWORK_.20

  block-storage-_NODE_NAME_:
    extends:
      file: docker-compose.test.base.yml
      service: block-storage
    environment:
      NODE_NAME: _NODE_NAME_
    networks: 
      _NODE_NAME_:
        ipv4_address: _PRIVATE_NETWORK_.19
    extra_hosts:
      - consensus:_PRIVATE_NETWORK_.15
      - public-api:_PRIVATE_NETWORK_.16
      - state-storage:_PRIVATE_NETWORK_.17
      - virtual-machine:_PRIVATE_NETWORK_.18
      - block-storage:_PRIVATE_NETWORK_.19
      - gossip:_PRIVATE_NETWORK_.20

  gossip-_NODE_NAME_:
    extends:
      file: docker-compose.test.base.yml
      service: gossip
    environment:
      NODE_NAME: _NODE_NAME_
      NODE_IP: _NODE_IP_
    networks: 
      common:
        ipv4_address: _NODE_IP_
      _NODE_NAME_:
        ipv4_address: _PRIVATE_NETWORK_.20
    volumes:
      - ./deploy/dummy-keys/private/_NODE_NAME_:/opt/orbs/config/topologies/discovery/node1/config/test-private-key
    extra_hosts:
      - consensus:_PRIVATE_NETWORK_.15
      - public-api:_PRIVATE_NETWORK_.16
      - state-storage:_PRIVATE_NETWORK_.17
      - virtual-machine:_PRIVATE_NETWORK_.18
      - block-storage:_PRIVATE_NETWORK_.19
      - gossip:_PRIVATE_NETWORK_.20
