version: '2'

services:
  base-service:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    restart: always
    command: node dist/index.js ${NODE_CONFIG_PATH}
    volumes:
      - ./logs:/opt/orbs/logs
      - ./config/topologies/discovery/node1:/opt/orbs/config/topology
    environment:
      NODE_NAME: ${NODE_NAME}
      NODE_ENV: test
      GOSSIP_PEERS: ws://172.2.1.2:60001,ws://172.2.1.3:60001,ws://172.2.1.4:60001,ws://172.2.1.5:60001,ws://172.2.1.6:60001,ws://172.2.1.7:60001
