version: '2'

services:
  e2e:
    extends:
      file: docker-compose.test.base.yml
      service: base-service
    working_dir: /opt/orbs/e2e
    environment:
      E2E_NO_DEPLOY: ${E2E_NO_DEPLOY}
      E2E_PUBLIC_API_ENDPOINT: ${PUBLIC_API_IP}:51151
    volumes:
      - ./e2e/test:/opt/orbs/e2e/test
      - /var/run/docker.sock:/var/run/docker.sock
    command: yarn test
    networks:
      public-api-external-network:
        ipv4_address: ${E2E_CLIENT_IP}
