FROM orbs:base-sdk

ENV PROJECT_TYPE=e2e

ARG AWS_ACCESS_KEY_ID

ARG AWS_SECRET_ACCESS_KEY

ADD docker/bootstrap-e2e.sh /opt/orbs/

RUN ./bootstrap-e2e.sh

ADD . /opt/orbs

RUN ./build-e2e.sh

WORKDIR /opt/orbs/e2e
