version: '2.1'
services:
  basic-simulation:
    build: .
    command: node simulate/src/index.js transaction-gossip
    volumes:
      - ./config:/opt/orbs/config/
      - ./projects/gossip-service-typescript/dist:/opt/orbs/projects/gossip-service-typescript/dist/
    networks:
      basic-network:

networks:
  basic-network:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
      - subnet: 172.1.1.0/24
