version: '2'

services:
  consensus:
    extends:
      file: docker-compose.test.base.yml
      service: base-service
    working_dir: /opt/orbs/projects/services/consensus-service-typescript/
    command: node dist/index.js ${NODE_CONFIG_PATH}/consensus.js
    networks:
      node-network:
        ipv4_address: ${PRIVATE_NETWORK}.15
    volumes_from:
      - shared_volumes
    extra_hosts:
      - consensus:${PRIVATE_NETWORK}.15
      - public-api:${PRIVATE_NETWORK}.16
      - storage:${PRIVATE_NETWORK}.17
      - virtual-machine:${PRIVATE_NETWORK}.18
      - gossip:${PRIVATE_NETWORK}.19

  public-api:
    extends:
      file: docker-compose.test.base.yml
      service: base-service
    working_dir: /opt/orbs/projects/services/public-api-service-typescript/
    command: node dist/index.js ${NODE_CONFIG_PATH}/public-api.js
    ports:
      - ${PUBLIC_API_HOST_PORT}:51151
    volumes_from:
      - shared_volumes
    networks:
      public-api-external-network:
        ipv4_address: ${PUBLIC_API_IP}
      node-network:
        ipv4_address: ${PRIVATE_NETWORK}.16
    extra_hosts:
      - consensus:${PRIVATE_NETWORK}.15
      - public-api:${PRIVATE_NETWORK}.16
      - storage:${PRIVATE_NETWORK}.17
      - virtual-machine:${PRIVATE_NETWORK}.18
      - gossip:${PRIVATE_NETWORK}.19

  storage:
    extends:
      file: docker-compose.test.base.yml
      service: base-service
    working_dir: /opt/orbs/projects/services/storage-service-typescript/
    command: node dist/index.js ${NODE_CONFIG_PATH}/storage.js
    volumes_from:
      - shared_volumes
    networks:
      node-network:
        ipv4_address: ${PRIVATE_NETWORK}.17
    extra_hosts:
      - consensus:${PRIVATE_NETWORK}.15
      - public-api:${PRIVATE_NETWORK}.16
      - storage:${PRIVATE_NETWORK}.17
      - virtual-machine:${PRIVATE_NETWORK}.18
      - gossip:${PRIVATE_NETWORK}.19

  virtual-machine:
    extends:
      file: docker-compose.test.base.yml
      service: base-service
    working_dir: /opt/orbs/projects/services/virtual-machine-service-typescript/
    command: node dist/index.js ${NODE_CONFIG_PATH}/virtual-machine.js
    volumes_from:
      - shared_volumes
    networks:
      node-network:
        ipv4_address: ${PRIVATE_NETWORK}.18
    extra_hosts:
      - consensus:${PRIVATE_NETWORK}.15
      - public-api:${PRIVATE_NETWORK}.16
      - storage:${PRIVATE_NETWORK}.17
      - virtual-machine:${PRIVATE_NETWORK}.18
      - gossip:${PRIVATE_NETWORK}.19

  gossip:
    extends:
      file: docker-compose.test.base.yml
      service: base-service
    working_dir: /opt/orbs/projects/services/gossip-service-typescript/
    command: node dist/index.js ${NODE_CONFIG_PATH}/gossip.js
    volumes_from:
      - shared_volumes
    networks:
      orbs-network:
        ipv4_address: ${NODE_IP}
      node-network:
        ipv4_address: ${PRIVATE_NETWORK}.19
    extra_hosts:
      - consensus:${PRIVATE_NETWORK}.15
      - public-api:${PRIVATE_NETWORK}.16
      - storage:${PRIVATE_NETWORK}.17
      - virtual-machine:${PRIVATE_NETWORK}.18
      - gossip:${PRIVATE_NETWORK}.19

  sidechain-connector:
    extends:
      file: docker-compose.test.base.yml
      service: base-service
    working_dir: /opt/orbs/projects/services/sidechain-connector-service-typescript/
    command: node dist/index.js ${NODE_CONFIG_PATH}/sidechain-connector.js --ethereumNodeHttpAddress=${SIDECHAIN_CONNECTOR__ETHEREUM_NODE_HTTP_ADDRESS}
    volumes_from:
      - shared_volumes
    networks:
      node-network:
        ipv4_address: ${PRIVATE_NETWORK}.20
    extra_hosts:
      - consensus:${PRIVATE_NETWORK}.15
      - public-api:${PRIVATE_NETWORK}.16
      - storage:${PRIVATE_NETWORK}.17
      - virtual-machine:${PRIVATE_NETWORK}.18
      - gossip:${PRIVATE_NETWORK}.19
      - sidechain-connector:${PRIVATE_NETWORK}.20

