/** Declaration file generated by dts-gen */

export function decode(string: string): Buffer;

export function decodeUnsafe(string: string): Buffer;

export function encode(source: Buffer): string;

export namespace decode {
    const prototype: {
    };
}

export namespace decodeUnsafe {
    const prototype: {
    };
}

export namespace encode {
    const prototype: {
    };
}

