/**
 * Copyright 2018 the orbs-network-typescript authors
 * This file is part of the orbs-network-typescript library in the Orbs project.
 *
 * This source code is licensed under the MIT license found in the LICENSE file in the root directory of this source tree.
 * The above notice should be included in all copies or substantial portions of the software.
 */

/** Declaration file generated by dts-gen */

export = gaggle;

declare function gaggle(opts: any): any;

declare namespace gaggle {
  const prototype: {
  };

  function enhanceServerForSocketIOChannel(server: any): any;

  namespace enhanceServerForSocketIOChannel {
    const prototype: {
    };
  }
}
