/** Declaration file generated by dts-gen */

export = grpc_caller;

declare function grpc_caller(host: any, proto: any, name?: any, options?: any): any;

declare namespace grpc_caller {
    const prototype: {
    };

    function metadata(metadata: any, options: any): any;

    namespace metadata {
        const prototype: {
        };

    }

}
