Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  config.vm.provision "shell", path: "bootstrap-local.sh"
  config.vm.synced_folder "../bootstrap", "/opt/orbs"
  config.vm.synced_folder "../../docker/images/", "/opt/docker/"
end
