
Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end

  config.vm.synced_folder "../../docker/images/", "/opt/docker/"
  config.vm.synced_folder "../bootstrap", "/opt/orbs"
  config.vm.synced_folder "../temp-keys/private-keys", "/opt/orbs/private-keys"

  config.vm.box = "generic/debian9"
  config.vm.provision "shell", path: "bootstrap-local.sh"
end
