version: '2'

services:
  consensus:
    extends:
      file: docker-compose.test.base.yml
      service: base-service
    working_dir: /opt/orbs/projects/services/consensus-service-typescript/
    command: node --inspect=0.0.0.0:9229 dist/index.js ${NODE_CONFIG_PATH}/consensus.js
    restart: always
    environment:
      - NUM_OF_NODES=${NUM_OF_NODES}
      - ETHEREUM_CONTRACT_ADDRESS=${SUBSCRIPTION_MANAGER_ETHEREUM_CONTRACT_ADDRESS}
      - SUBSCRIPTION_PROFILES=${SUBSCRIPTION_PROFILES}
      - BLOCK_BUILDER_POLL_INTERVAL=500
      - MIN_ELECTION_TIMEOUT=20000000
      - MAX_ELECTION_TIMEOUT=40000000
      - HEARBEAT_INTERVAL=100
      - TRANSACTION_EXPIRATION_TIMEOUT=240000
      - MSG_LIMIT=4000000
      - BLOCK_SIZE_LIMIT=2000
      - BLOCK_SIZE_MIN=100
      - LEADER_SYNC_INTERVAL=100
      - CONSENSUS_ALGORITHM=pbft
      - GENERATE_KEYS=${GENERATE_KEYS}
      - CONSENSUS_LEADER_NODE_NAME=node2
      - VERIFY_SUBSCRIPTION=true
    ports:
      - ${DEBUG_PORT}:9229
    networks:
      node-network:
        ipv4_address: ${PRIVATE_NETWORK}.15
    volumes_from:
      - shared_volumes
    volumes:
      - ./public-keys/consensus:/opt/orbs/public-keys/consensus
      - ./private-keys/consensus:/opt/orbs/private-keys/consensus
    extra_hosts:
      - consensus:${PRIVATE_NETWORK}.15
      - public-api:${PRIVATE_NETWORK}.16
      - storage:${PRIVATE_NETWORK}.17
      - virtual-machine:${PRIVATE_NETWORK}.18
      - gossip:${PRIVATE_NETWORK}.19
      - sidechain-connector:${PRIVATE_NETWORK}.20

  public-api:
    extends:
      file: docker-compose.test.base.yml
      service: base-service
    working_dir: /opt/orbs/projects/services/public-api-service-typescript/
    command: node  --inspect=0.0.0.0:9229 dist/index.js ${NODE_CONFIG_PATH}/public-api.js
    restart: always
    ports:
      - ${PUBLIC_API_HOST_PORT}:51151
      - ${PUBLIC_API_HOST_HTTP_PORT}:80
    volumes_from:
      - shared_volumes
    networks:
      public-network:
        ipv4_address: ${PUBLIC_API_IP}
      node-network:
        ipv4_address: ${PRIVATE_NETWORK}.16
    extra_hosts:
      - consensus:${PRIVATE_NETWORK}.15
      - public-api:${PRIVATE_NETWORK}.16
      - storage:${PRIVATE_NETWORK}.17
      - virtual-machine:${PRIVATE_NETWORK}.18
      - gossip:${PRIVATE_NETWORK}.19

  storage:
    extends:
      file: docker-compose.test.base.yml
      service: base-service
    working_dir: /opt/orbs/projects/services/storage-service-typescript/
    command: node dist/index.js ${NODE_CONFIG_PATH}/storage.js
    restart: always
    environment:
      BLOCK_STORAGE_POLL_INTERVAL: 20000
    volumes_from:
      - shared_volumes
    networks:
      node-network:
        ipv4_address: ${PRIVATE_NETWORK}.17
    extra_hosts:
      - consensus:${PRIVATE_NETWORK}.15
      - public-api:${PRIVATE_NETWORK}.16
      - storage:${PRIVATE_NETWORK}.17
      - virtual-machine:${PRIVATE_NETWORK}.18
      - gossip:${PRIVATE_NETWORK}.19

  virtual-machine:
    extends:
      file: docker-compose.test.base.yml
      service: base-service
    working_dir: /opt/orbs/projects/services/virtual-machine-service-typescript/
    environment:
      - SMART_CONTRACTS_TO_LOAD=${VIRTUAL_MACHINE_SMART_CONTRACTS_TO_LOAD}
    command: node --inspect=0.0.0.0:9229 dist/index.js ${NODE_CONFIG_PATH}/virtual-machine.js
    restart: always
    volumes_from:
      - shared_volumes
    networks:
      node-network:
        ipv4_address: ${PRIVATE_NETWORK}.18
    extra_hosts:
      - consensus:${PRIVATE_NETWORK}.15
      - public-api:${PRIVATE_NETWORK}.16
      - storage:${PRIVATE_NETWORK}.17
      - virtual-machine:${PRIVATE_NETWORK}.18
      - gossip:${PRIVATE_NETWORK}.19

  gossip:
    extends:
      file: docker-compose.test.base.yml
      service: base-service
    working_dir: /opt/orbs/projects/services/gossip-service-typescript/
    restart: always
    environment:
      - NODE_IP=${NODE_IP}
    command: node --inspect=0.0.0.0:9229 dist/index.js ${NODE_CONFIG_PATH}/gossip.js
    volumes_from:
      - shared_volumes
    networks:
      orbs-network:
        ipv4_address: ${NODE_IP}
      node-network:
        ipv4_address: ${PRIVATE_NETWORK}.19
    extra_hosts:
      - consensus:${PRIVATE_NETWORK}.15
      - public-api:${PRIVATE_NETWORK}.16
      - storage:${PRIVATE_NETWORK}.17
      - virtual-machine:${PRIVATE_NETWORK}.18
      - gossip:${PRIVATE_NETWORK}.19

  sidechain-connector:
    extends:
      file: docker-compose.test.base.yml
      service: base-service
    working_dir: /opt/orbs/projects/services/sidechain-connector-service-typescript/
    restart: always
    environment:
    - ETHEREUM_NODE_HTTP_ADDRESS=${SIDECHAIN_CONNECTOR_ETHEREUM_NODE_HTTP_ADDRESS}
    command: node dist/index.js ${NODE_CONFIG_PATH}/sidechain-connector.js
    volumes_from:
      - shared_volumes
    networks:
      public-network:
        ipv4_address: ${SIDECHAIN_CONNECTOR_PUBLIC_IP}
      node-network:
        ipv4_address: ${PRIVATE_NETWORK}.20
    extra_hosts:
      - consensus:${PRIVATE_NETWORK}.15
      - public-api:${PRIVATE_NETWORK}.16
      - storage:${PRIVATE_NETWORK}.17
      - virtual-machine:${PRIVATE_NETWORK}.18
      - gossip:${PRIVATE_NETWORK}.19
      - sidechain-connector:${PRIVATE_NETWORK}.20
