/** Declaration file generated by dts-gen */

export as namespace ip_cidr;

export = CIDR;

declare class CIDR {
    constructor(...args: any[]);

    arrayAction(...args: any[]): any[];

    end(...args: any[]): string;

    formatIP(...args: any[]): string;

    getChunkInfo(...args: any[]): any;

    isValid(...args: any[]): boolean;

    start(...args: any[]): string;

    toArray(...args: any[]): any;

    toObject(...args: any[]): any;

    toRange(...args: any[]): any;

    toString(...args: any[]): string;

}