version: '2'

services:
  app:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    working_dir: /opt/orbs/client/examples/event-proxy-app
    command: yarn run server
    restart: always
    ports:
      - 80:8080
    environment:
      ORBS_API_ENDPOINT: http://us-east-1.global.nodes.staging.orbs-test.com
      REDIS_URL: redis://redis:6379
    links:
      - redis:redis

  redis:
    image: redis
    restart: always
    volumes:
      - ./data:/data
